upstream store-server {
    server store-server:8082;
}

upstream store-app {
    server store-app:4173;
}

server {
    listen 80;
    listen [::]:80;

    location / {           
        proxy_pass http://store-app;
        proxy_http_version 1.1;
        proxy_set_header    Origin http://$http_host;
        proxy_set_header    Host $http_host;
    }
}